SUPPORTED_PLATFORMS = ['macOS']
EXTENSIONS = ['mp3', 'wav', 'm4a']
SRT_TAGS = {
    'vrsn': 'Version',
    'otrk': 'Track',
    'ttyp': 'Type',
    'pfilv': 'Filename',
    'pfil': 'Filename',
    'tsng': 'Song',
    'tart': 'Artist',
    'talb': 'Album',
    'tgen': 'Genre',
    'tlen': 'Length',
    'tcmp': 'Composer',
    'tsiz': 'Size',
    'tbit': 'Bitrate',
    'tsmp': 'Sampling',
    'tbpm': 'BPM',
    'tcom': 'Comment',
    'trmx': 'Remixer',
    'ttyr': 'Year',
    'tadd': 'Date Added',
    'tkey': 'Key',
    'uadd': '',
    'ulbl': '',
    'utme': '',
    'utpc': '',
    'sbav': '',
    'bhrt': '',
    'bmis': '',
    'bply': '',
    'blop': '',
    'bitu': '',
    'bovc': '',
    'bcrt': '',
    'biro': '',
    'bwlb': '',
    'bwll': '',
    'buns': '',
    'bbgl': '',
    'bkrk': '',
    'tlbl': 'Label',
    'utkn': 'Track #',
    'tgrp': 'Grouping',
    'ufsb': '',
    'udsc': '',
    'ptrk': 'Track'
}

